apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crest-data
  labels:
    app.kubernetes.io/name: crest
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
