version: '3'
services:

  mysql-de:
    image: ghcr.io/sevoniva/crest-mysql:8.4.5
    container_name: mysql-de
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u${DE_MYSQL_USER}", "-p${DE_MYSQL_PASSWORD}", "--protocol","tcp"]
      interval: 5s
      timeout: 3s
      retries: 10
    env_file:
      - ${DE_BASE}/dataease2.0/conf/mysql.env
    volumes:
      - ${DE_BASE}/dataease2.0/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ${DE_BASE}/dataease2.0/bin/mysql:/docker-entrypoint-initdb.d/
      - ${DE_BASE}/dataease2.0/data/mysql:/var/lib/mysql
    networks:
      - dataease-network

  dataease:
    image: ghcr.io/sevoniva/crest:DE_TAG
    stop_signal: SIGTERM
    stop_grace_period: 15s
    container_name: dataease
    ports:
      - ${DE_PORT}:8100
    volumes:
      - ${DE_BASE}/dataease2.0/conf:/opt/apps/config
      - ${DE_BASE}/dataease2.0/logs:/opt/dataease2.0/logs
      - ${DE_BASE}/dataease2.0/data/static-resource:/opt/dataease2.0/data/static-resource
      - ${DE_BASE}/dataease2.0/cache:/opt/dataease2.0/cache
      - ${DE_BASE}/dataease2.0/data/appearance:/opt/dataease2.0/data/appearance
      - ${DE_BASE}/dataease2.0/data/exportData:/opt/dataease2.0/data/exportData
      - ${DE_BASE}/dataease2.0/data/font:/opt/dataease2.0/data/font
      - ${DE_BASE}/dataease2.0/data/i18n:/opt/dataease2.0/data/i18n
    depends_on:
      mysql-de:
        condition: service_healthy
    networks:
      - dataease-network

networks:
  dataease-network:
