
spring:

  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848
  datasource:
    url: ${CREST_DB_URL:jdbc:mysql://localhost:3306/crest?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false}
    username: ${CREST_DB_USERNAME:root}
    password: ${CREST_DB_PASSWORD:}
  flyway:
    enabled: false
  messages:
    basename: i18n/core


dynamic:
  datasource:
    official-ds:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${CREST_OFFICIAL_DB_URL:jdbc:mysql://localhost:3306/crest_official?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false}
      username: ${CREST_OFFICIAL_DB_USERNAME:${CREST_DB_USERNAME:root}}
      password: ${CREST_OFFICIAL_DB_PASSWORD:${CREST_DB_PASSWORD:}}

mybatis-plus:
  mapper-locations: classpath:mybatis/*.xml
