# 基础配置
DE_BASE=/opt
DE_PORT=8100
DE_LOGIN_TIMEOUT=960
DE_CONTEXT_PATH=

# 数据库配置
DE_MYSQL_HOST=mysql-de
DE_MYSQL_PORT=3306
DE_MYSQL_DB=dataease
DE_MYSQL_USER=root
DE_MYSQL_PASSWORD=Password123@mysql
DE_MYSQL_PARAMS="autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true"

# 导出限制
DE_EXPORT_VIEWS_LIMIT=100000
DE_EXPORT_DATASET_LIMIT=100000
DE_ORIGIN_LIST="http://localhost:8000"
